services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: yarn dev
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./internal:/app/internal
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./internal:/app/internal
    command: yarn start:dev
    ports:
      - "3002:3002"
    restart: always

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db_dumps/:/db_dumps
      - ./pgdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: geraldisriviiA1

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: geraldisriviiA1
      ME_CONFIG_MONGODB_URL: mongodb://root:geraldisriviiA1@mongo:27017/
      ME_CONFIG_BASICAUTH: false
