FROM node:20-alpine

WORKDIR /app/apps/frontend


COPY /apps/frontend/package.json .
RUN npm install -g yarn --force
RUN yarn install

COPY ./apps/frontend /app/apps/frontend
COPY ./internal /app/internal
